apiVersion: v1
kind: Service
metadata:
  name: pinkapp
  labels:
   app: pinkapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pinkapp
  type: LoadBalancer

